version: '3.1'

services: 
  webserver: 
    image: nginx:latest
    container_name: nginx-prod
    volumes:
      - /home/ruben/workspace/uniandes/proyecto0/infra/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/ruben/workspace/uniandes/proyecto0/frontend/build:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
#   networks:
#      - webnet
  database:
    image: postgres
    restart: always
    container_name: "postgresql-prod"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: dev
    volumes:
      - postgresql-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
#    networks:
#      - webnet
  backend:
    container_name: "backend-prod"
    build:
      context: /home/ruben/workspace/uniandes/proyecto0/backend
      dockerfile: Dockerfile
    ports:
      - 9001:9001
#    networks:
#      - webnet
#  npm-build:
#    container_name: npm-build
#    build:
#      context: /home/ruben/workspace/uniandes/proyecto0/frontend
#      dockerfile: Dockerfile
#    volumes:
#      - /home/ruben/workspace/uniandes/proyecto0/frontend:/app
#      - /app/node_modules
networks:
  webnet:
volumes:
  postgresql-db:
#  webapp-build:
