version: '3.1'

services: 
  webserver: 
    image: nginx:latest
    container_name: nginx-pdn
    depends_on:
      - eventos
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../frontend/build:/usr/share/nginx/html
    hostname: webserver
    networks: 
      - frontend
    ports:
      - 8080:8080
      - 443:443
  eventos:
    image: openjdk:8
    container_name: events-pdn
    depends_on:
      - database
    volumes:
      - ../backend/eventos-1.0:/opt/eventos
      - ../backend/logs:/opt/eventos/logs  
    hostname: eventos   
    networks: 
      - backend
      - frontend
    ports:
      - 9001:9001
    environment:
      TZ: "America/Bogota"
      LANG: "C.UTF-8"
    restart: always
    command: "bash ./opt/eventos/bin/eventos -J-server -J-Xms512m -J-Xmx512m"
  database:
    image: postgres
    container_name: postgresql-pdn
    hostname: database
    networks: 
      - backend
    ports:
      - 5432:5432   
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: dev
    restart: always
    volumes:
      - postgresql-db:/var/lib/postgresql/data
networks:
  backend:
  frontend:
volumes:
  postgresql-db: