# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: "my_postgres"
    environment:
      POSTGRES_PASSWORD: example
    ports:
        - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
  webapp:
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
       - '80:80'
    environment:
      - APP_ENV=development
volumes:
  my_dbdata:
